HW7: Farruh Sheripov
tamkovich/tms-python-summer pull request #29
Opened 2020-07-24 22:39 UTC by Sheripov

complate HW7

2020-07-27 12:10 UTC, tamkovich requested changes
Спасибо за работу,

Пожалуйста, проверьте и поправьте пункты ниже из [чеклиста](https://github.com/tamkovich/tms-python-summer/blob/homework_reviews/Homework%20Reviews/HW7.md)

8, 12, 14, 15

2020-07-27 12:15 UTC, tamkovich requested changes

2020-07-27 12:15 UTC, tamkovich commented on src/task_7_1.py
> +# 1. Дюймы в сантиметры
Пункт 12

```python
def inch_to_sm(a):
    """
    1. Дюймы в сантиметры
    """
```

2020-07-27 12:15 UTC, tamkovich commented on src/task_7_1.py
> +    except ValueError:
Пункт 8

Лучше до всех ифов сделать проверку:
```python
try:
    number = float(input('input number: '))
except ValueError:
    print('error input!')
```

В таком случае код будет читабельнее и в блок try-except точно не попадут ошибки, которые могли произойти внутри функций, например

2020-07-27 12:15 UTC, tamkovich commented on src/task_7_1.py
> +            continue
Здесь continue уже не нужен :)

2020-07-28 12:02 UTC, tamkovich requested changes
Все ок, только поправить проверку на choose. 

В твоем случае будет создаваться отдельный список, а это лишняя память. Написал вариант оптимизированнее

2020-07-28 12:02 UTC, tamkovich commented on src/task_7_1.py
> +        if int(choose) not in range(1, 13):
```suggestion
        if 0 < int(choose) < 13:
```

2020-07-28 20:19 UTC, Sheripov commented on src/task_7_1.py
> +        if int(choose) not in range(1, 13):
Мне же нужно чтобы if выводил надпись ошибки типа error input in range 1-12! 
У меня проверка делается локально. Если сделать так как вы написали придется весь остальной код засунуть под if

2020-07-29 09:13 UTC, tamkovich approved these changes

2023-10-19 10:47 UTC, closed without merging