Valento 8
tamkovich/tms-python-summer pull request #32
Opened 2020-07-25 11:11 UTC by Lex-23

2020-07-28 12:50 UTC, tamkovich requested changes
Спасибо за работу,

Пожалуйста, проверьте и поправьте пункты ниже из [чеклиста](https://github.com/tamkovich/tms-python-summer/blob/homework_reviews/Homework%20Reviews/HW8.md)

5, 16

2020-07-28 12:50 UTC, tamkovich commented on src/task_8/task_8_1.py
> +    elif n % 2 == 0:
```suggestion
    else:
```

2020-07-28 12:50 UTC, tamkovich commented on src/task_8/task_8_2.py
> +    return palindrom_words
Попробуйте использовать генератор списков

```suggestion
    return [i for i in x if i == i[::-1]]
```

2020-07-28 12:50 UTC, tamkovich commented on src/task_8/task_8_2.py
> +    :return: new list
Опиши детальнее что такое содержит x и результат.

Список который содержит строки, можно обозначить так:

x: list[str]

2020-07-28 12:50 UTC, tamkovich commented on src/task_8/task_8_3.py
> +    return result
```suggestion
                return result
```

2020-07-28 12:50 UTC, tamkovich commented on src/task_8/task_8_3.py
> +        print("Error! e must be > 0")
В таком случае вывод будет выглядеть так:

>>>
"Error! e must be > 0"
'sin от 10 = None при точности -1'

Поправь, чтобы не выводилось внутри результата None

2020-07-28 16:01 UTC, Lex-23 commented on src/task_8/task_8_3.py
> +        print("Error! e must be > 0")
не могу понять два последних замечания. Ломал голову, но не понял зачем передвигать return вправо на 2 таба, ведь это неправильно относительно всей функции, от этого следовательно и вылазит None при любом значении, потомучто return стоит не там.

2020-07-29 09:22 UTC, tamkovich requested changes

2020-07-29 09:22 UTC, tamkovich commented on src/task_8/task_8_3.py
> +        print("Error! e must be > 0")
При текущем решении,  программа будет заканчиватьсь с ошибкой в случае когда:

sin1(<любое число>, -10)

2020-07-29 09:22 UTC, tamkovich commented on src/task_8/task_8_3.py
> +def sin1(x: float, e: list) -> float:
В е будет содержаться не список значение, а только одно значение

```suggestion
def sin1(x: float, e: float) -> float:
```

2020-07-29 09:22 UTC, tamkovich commented on src/task_8/task_8_3.py
> +    :param e > 0: list. (список значений точности, по которым высчитыввется приближенное значение синуса)
В е будет содержаться не список значение, а только одно значение

```suggestion
    :param e > 0: float. (список значений точности, по которым высчитыввется приближенное значение синуса)
```

2020-08-02 16:35 UTC, tamkovich requested changes
Все ок, только поправь плиз оставшиеся комментарии

2023-05-10 10:47 UTC, closed without merging