added Homework 5
tamkovich/tms-python-summer pull request #6
Opened 2020-07-20 19:01 UTC by Sheripov

2020-07-22 11:59 UTC, tamkovich requested changes
Спасибо за работу,

Пожалуйста, проверьте и поправьте пункты ниже из [чеклиста](https://github.com/tamkovich/tms-python-summer/blob/homework_reviews/Homework%20Reviews/HW5.md)

13, 15, 17, 20

2020-07-22 11:59 UTC, tamkovich commented on src/task_5_1.py
> +            continue
continue на последней строке цикла не нужен

2020-07-22 11:59 UTC, tamkovich commented on src/task_5_4.py
> +n = int(input("input natural numb: "))
Пункт 5

2020-07-24 20:20 UTC, Sheripov commented on src/task_5_1.py
> +            continue
поправил

2020-07-24 20:20 UTC, Sheripov commented on src/task_5_4.py
> +n = int(input("input natural numb: "))
поправил

2020-07-28 11:46 UTC, tamkovich approved these changes
LGTM

2020-08-03 16:34 UTC, closed without merging