lesson_07
tamkovich/tms-python-summer pull request #9
Opened 2020-07-20 19:04 UTC by andkot

2020-07-22 12:47 UTC, tamkovich requested changes
Спасибо за работу,

Пожалуйста, проверьте и поправьте пункты ниже из [чеклиста](https://github.com/tamkovich/tms-python-summer/blob/homework_reviews/Homework%20Reviews/HW5.md)

14

2020-07-22 12:47 UTC, tamkovich commented on src/lesson_07/task_5_1.py
> +            continue
Это конце цикла, нет смысла оставлять здесь continue

2020-07-22 12:47 UTC, tamkovich commented on src/lesson_07/task_5_5.py
> +import random
import random в шапку файла перед вункциями

2020-07-22 19:04 UTC, andkot commented on src/lesson_07/task_5_5.py
> +import random
Исправил

2020-07-22 19:04 UTC, andkot commented on src/lesson_07/task_5_1.py
> +            continue
Исправил

2020-07-27 13:05 UTC, tamkovich approved these changes
LGTM

2020-09-01 18:58 UTC, closed without merging