HW15: Farruh Sheripov
tamkovich/tms-python-summer pull request #90
Opened 2020-09-03 15:50 UTC by Sheripov

2020-09-03 21:46 UTC, tamkovich requested changes
Спасибо за работу, круто

**Добавить/поправить:**
- requirements.txt: django
- базу данных: postgres
- Сделать все запросы  create/update/delete через Class Based View
- добавить typing
- добавить проверку антефикации

2020-09-05 11:43 UTC, tamkovich requested changes

2020-09-05 11:43 UTC, tamkovich commented on src/taskmanager/main/models.py
> +        return reverse('index')
Он должен вернуть ссылку на сам продукт, а сейчас он вернет ссылку на url c name='index'

2020-09-05 11:43 UTC, tamkovich commented on src/taskmanager/taskmanager/settings.py
> +        'PORT': '5432',
Вынеси в какой-нибудь файл, и читай креды из файла. Типо config.txt/json/yaml

лучше убирать креды из кода программы)

2020-09-05 12:29 UTC, Sheripov commented on src/taskmanager/taskmanager/settings.py
> +        'PORT': '5432',
Готов

2020-09-05 12:59 UTC, Sheripov commented on src/taskmanager/main/models.py
> +        return reverse('index')
вроде сделал но не знаю правильно ли сделал

2023-10-19 10:47 UTC, closed without merging