TEST: Farruh Sheripov
tamkovich/tms-python-summer pull request #98
Opened 2020-09-13 09:25 UTC by Sheripov

2020-09-14 07:47 UTC, tamkovich requested changes
👍

2020-09-14 07:47 UTC, tamkovich commented on src/test.py
> +    def __init__(self):
```suggestion
    def __init__(self, time_from: time, ...):
```

2020-09-14 07:47 UTC, tamkovich commented on src/test.py
> +            time_from=time(10, 00, 00),
оформи тесты как юнитесты в отдельном модуле https://pythonworld.ru/moduli/modul-unittest.html

2020-09-14 07:47 UTC, tamkovich commented on src/test.py
> +        return 'не пересекают'
Вместо слов пересекают и нет пускай кидается True/False или True/raise Exception

2020-09-15 10:25 UTC, Sheripov commented on src/test.py
> +    def __init__(self):
готов

2020-09-15 10:25 UTC, Sheripov commented on src/test.py
> +        return 'не пересекают'
готов

2020-09-16 08:15 UTC, Sheripov commented on src/test.py
> +            time_from=time(10, 00, 00),
готов

2023-10-19 10:47 UTC, closed without merging